apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lidarr
  namespace: media
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: lidarr
  endpoints:
    - port: metrics
      scheme: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
